# Generated by Django 3.0.7 on 2020-06-25 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], default='sell', max_length=20)),
                ('category', models.CharField(choices=[('agriculture and food', 'Agriculture & Food'), ('animal and pets', 'Animal & Pets'), ('babies and kids', 'Babies & Kids'), ('commercial equipment and tools', 'Commercial Equipment & Tools'), ('electronics and computers', 'Electronics & Computers'), ('fashion', 'Fashion'), ('health and beauty', 'Health & Beauty'), ('home furniture and appliances', 'Home Furniture & Appliances'), ('mobile phones and tablets', 'Mobile Phones & Tablets'), ('property', 'Property'), ('construction materials and equipment', 'Construction Materials & Equipment'), ('sports arts and outdoors', 'Sports Arts & Outdoors'), ('vehicles', 'Vehicles')], max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('detail', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, upload_to=posts.models.upload_location)),
                ('currency', models.CharField(choices=[('ksh', 'Ksh'), ('usd', 'USD')], default='ksh', max_length=20)),
                ('price', models.CharField(max_length=30)),
                ('date_published', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
