# Generated by Django 3.0.7 on 2020-07-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200702_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ManyToManyField(to='posts.Type'),
        ),
    ]
