# Generated by Django 3.0.7 on 2020-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200703_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
