# Generated by Django 3.0.7 on 2020-07-09 13:45

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200709_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=places.fields.PlacesField(max_length=255),
        ),
    ]
