# Generated by Django 3.0.7 on 2020-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200806_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
