# Generated by Django 3.0.7 on 2020-08-27 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20200826_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostDislike',
            new_name='GroupPostDislike',
        ),
        migrations.RenameModel(
            old_name='PostLike',
            new_name='GroupPostLike',
        ),
        migrations.AlterField(
            model_name='grouppostdislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.GroupPost'),
        ),
        migrations.AlterField(
            model_name='grouppostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.GroupPost'),
        ),
    ]
