# Generated by Django 3.0.7 on 2020-08-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_reportedgrouppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('PROFILE_PIC', 'PROFILE_PIC'), ('BG_PIC', 'BG_PIC')], max_length=100)),
                ('image', models.ImageField(upload_to='defaultImg')),
            ],
        ),
    ]
