# Generated by Django 3.0.7 on 2020-08-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_defaultimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='defaultimage',
            name='image_type',
        ),
        migrations.AddField(
            model_name='defaultimage',
            name='bg_image',
            field=models.ImageField(default=1, upload_to='defaultImg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultimage',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='defaultImg'),
            preserve_default=False,
        ),
    ]
