# Generated by Django 3.0.7 on 2020-09-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_buyproposals_hirecomment_sellproposals_workproposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_promotional', '-date_published']},
        ),
    ]
