# Generated by Django 3.0.7 on 2020-11-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published']},
        ),
    ]
