# Generated by Django 3.0.7 on 2021-03-18 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0040_auto_20210218_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingfeedback',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='userinterest',
            name='sub_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ManyToManyField(related_name='category', to='posts.Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='postrating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='ratingfeedback',
            name='userrating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_feedback', to='posts.PostRating'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
