# Generated by Django 3.0.7 on 2021-03-24 07:46

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20210318_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=posts.models.upload_location_new),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimages', to='posts.Post'),
        ),
    ]
