# Generated by Django 3.0.7 on 2021-03-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201010_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='chat.Chat'),
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='chat.Chat'),
        ),
    ]
