# Generated by Django 3.0.7 on 2020-07-23 17:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200723_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_location),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location),
        ),
    ]
