# Generated by Django 3.0.7 on 2020-07-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200724_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendAccount',
        ),
    ]
