# Generated by Django 3.0.7 on 2020-10-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default=10, max_length=200),
        ),
    ]
