# Generated by Django 3.0.7 on 2021-03-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='country_code',
        ),
    ]
