# Generated by Django 3.0.7 on 2021-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country_code',
            field=models.CharField(max_length=5, null=True, verbose_name='country_code'),
        ),
    ]
