# Generated by Django 3.0.7 on 2021-03-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
