# Generated by Django 3.0.7 on 2021-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210328_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='account',
            name='explore_locations',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='explore_locations'),
        ),
    ]
